---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cb-lobby-ingress
  namespace: group2
  annotations:
    nginx.ingress.kubernetes.io/default-backend: cb-lobby:8888
spec:
  rules:
    - host: group2.sempro0.uvm.sdu.dk
      http:
        paths:
          - backend:
              service:
                name: cb-lobby-svc
                port:
                  number: 8888
            pathType: Prefix
            path: /

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cb-room-dep
  labels:
    app: cb-room
spec:
  selector:
      matchLabels:
        app: cb-room
  replicas: 1
  template:
    metadata:
      labels:
        app: cb-room
    spec:
      containers:
      - name: cb-room
        image: benjaminhck/coffeebreak-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # livenessProbe:
        #   httpGet:
        #     path: /status
        #     port: 5000
        #   initialDelaySeconds: 3
        #   periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: cb-room-svc
spec:
  type: LoadBalancer
  selector:
    app: cb-room
  ports:
     -  protocol: TCP
        name: https
        port: 8074
        targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: cb-lobby
  labels:
    app: cb-lobby
spec:
  serviceAccountName: group2-user
  containers:
    - name: cb-lobby
      image: benjaminhck/coffeebreak-web:latest
      ports:
        - containerPort: 80
      # readinessProbe:
      #   httpGet:
      #     path: /
      #     port: 8443
      #     scheme: HTTPS
      #   initialDelaySeconds: 5
      #   periodSeconds: 10
      # livenessProbe:
      #   tcpSocket:
      #     port: 8443
      #   initialDelaySeconds: 15
      #   periodSeconds: 20
      
---
apiVersion: v1
kind: Service
metadata:
  name: cb-lobby-svc
spec:
  type: LoadBalancer
  selector:
    app: cb-lobby
  ports:
     -  protocol: TCP
        name: http
        port: 8888
        targetPort: 80         
