---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-coffeebreak
  namespace: group2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.org/websocket-services: "svc-lobby"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

spec:
  rules:
    - host: group2.sempro0.uvm.sdu.dk
      http:
        paths:
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: svc-lobby
                port:
                  number: 8888
            
          - path: /ws()(.*)
            pathType: Prefix
            backend:
              service:
                name: svc-lobby
                port:
                  number: 8082    

---
apiVersion: v1
kind: Pod
metadata:
  name: lobby
  labels:
    app: lobby
spec:
  serviceAccountName: group2-user
  containers:
    - name: con-lobby
      image: benjaminhck/coffeebreak-lobby:latest
      ports:
        - containerPort: 80
        - containerPort: 8082
      
      # readinessProbe:
      #   httpGet:
      #     path: /
      #     port: 8443
      #     scheme: HTTPS
      #   initialDelaySeconds: 5
      #   periodSeconds: 10
      # livenessProbe:
      #   tcpSocket:
      #     port: 8443
      #   initialDelaySeconds: 15
      #   periodSeconds: 20
      
---
apiVersion: v1
kind: Service
metadata:
  name: svc-lobby
spec:
  type: LoadBalancer
  selector:
    app: lobby
  ports:
    - protocol: TCP
      name: web
      port: 8888
      targetPort: 80

    - protocol: TCP
      name: socket
      port: 8082
      targetPort: 8082
