---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-coffeebreak
  namespace: group2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: group2.sempro0.uvm.sdu.dk
      http:
        paths:
          - backend:
              service:
                name: svc-lobby
                port:
                  number: 8888
            pathType: Prefix
            path: /()(.*)

---
apiVersion: v1
kind: Pod
metadata:
  name: lobby
  labels:
    app: lobby
spec:
  serviceAccountName: group2-user
  containers:
    - name: con-lobby
      image: benjaminhck/coffeebreak-lobby:latest
      ports:
        - containerPort: 80
      # readinessProbe:
      #   httpGet:
      #     path: /
      #     port: 8443
      #     scheme: HTTPS
      #   initialDelaySeconds: 5
      #   periodSeconds: 10
      # livenessProbe:
      #   tcpSocket:
      #     port: 8443
      #   initialDelaySeconds: 15
      #   periodSeconds: 20
      
---
apiVersion: v1
kind: Service
metadata:
  name: svc-lobby
spec:
  type: LoadBalancer
  selector:
    app: lobby
  ports:
     -  protocol: TCP
        name: http
        port: 8888
        targetPort: 80         
