---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeebreak-deployment
  labels:
    app: coffeebreak
spec:
  selector:
      matchLabels:
        app: coffeebreak
  replicas: 2
  template:
    metadata:
      labels:
        app: coffeebreak
    spec:
      containers:
      - name: coffeebreak
        image: benjaminhck/coffeebreak:latest
        ports:
        - containerPort: 8080
        # livenessProbe:
        #   httpGet:
        #     path: /status
        #     port: 5000
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
#NOTE: comment out `volumeMounts` section for configmap and\or secret guide
        # volumeMounts:
        # - name: secret-volume
        #   mountPath: /secrets/
        # - name: config-volume
        #   mountPath: /configs/
#NOTE: comment out `volumes` section for configmap and\or secret guide
      # volumes:
      # - name: secret-volume
      #   secret:
      #     secretName: mysecret
      # - name: config-volume
      #   configMap:
      #     name: example-config #name of our configmap object